name: Build and publish
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y devscripts debhelper

      - name: Package Limoji
        run: dpkg-buildpackage --build=binary --no-check-builddeps --compression=gzip

      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          tag: "v1"
          artifacts: ../*.deb
          token: ${{ secrets.PERSONAL_TOKEN }}
