name: Build and publish
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y devscripts debhelper

      - name: Package Limoji
        run: dpkg-buildpackage --build=binary --no-check-builddeps

      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ../*.deb
          draft: true
          token: ${{ secrets.personal_token }}

      - name: Upload to Gemfury
        run: curl -F package=@$(find ../ -type f -name "*.deb") https://${{ secrets.gemfury_token }}@push.fury.io/lefterisgar/
